# Generated by Django 5.2.3 on 2025-06-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
