# Generated by Django 5.2.3 on 2025-06-18 12:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courseschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='day_of_week',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DU', 'Dushanba'), ('SE', 'Seshanba'), ('CH', 'Chorshanba'), ('PA', 'Payshanba'), ('JU', 'Juma'), ('SH', 'Shanba'), ('YA', 'Yakshanba')], max_length=10), size=17, verbose_name='Hafta kunlari'),
        ),
    ]
