# Generated by Django 5.2.3 on 2025-06-18 12:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_courseschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseschedule',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='courseschedule',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='day_of_week',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DU', 'Dushanba'), ('SE', 'Seshanba'), ('CH', 'Chorshanba'), ('PA', 'Payshanba'), ('JU', 'Juma'), ('SH', 'Shanba'), ('YA', 'Yakshanba')], max_length=2), default=list, size=7),
        ),
    ]
