# Generated by Django 5.2.3 on 2025-06-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_courseschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseschedule',
            options={'ordering': ['day_of_week', 'start_time']},
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='day_of_week',
            field=models.CharField(choices=[('DU', 'Dushanba'), ('SE', 'Seshanba'), ('CH', 'Chorshanba'), ('PA', 'Payshanba'), ('JU', 'Juma'), ('SH', 'Shanba'), ('YA', 'Yakshanba')], max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='courseschedule',
            unique_together={('course', 'day_of_week', 'start_time')},
        ),
    ]
