# Generated by Django 5.2.3 on 2025-06-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_courseschedule_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSchedule',
        ),
    ]
