# Generated by Django 5.2.3 on 2025-06-18 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_delete_courseschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(help_text='YouTube video havolasi')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Resource',
                'verbose_name_plural': 'Course Resources',
            },
        ),
    ]
