# Generated by Django 5.2.3 on 2025-07-28 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0033_alter_story_expires_at'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDayTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('du', 'Dushanba'), ('se', 'Seshanba'), ('ch', 'Chorshanba'), ('pa', 'Payshanba'), ('ju', 'Juma'), ('sh', 'Shanba'), ('ya', 'Yakshanba')], max_length=2)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='centers.teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='days',
            field=models.ManyToManyField(related_name='groups', to='student.groupdaytime'),
        ),
    ]
