# Generated by Django 5.2.3 on 2025-06-18 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0015_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 13, 8, 22, 558575, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='CourseSchedule',
        ),
    ]
