# Generated by Django 5.2.3 on 2025-06-19 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0020_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 20, 12, 56, 48, 789278, tzinfo=datetime.timezone.utc)),
        ),
    ]
