# Generated by Django 5.2.3 on 2025-06-21 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0023_alter_story_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default="Noma'lum", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(default="Noma'lum", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 8, 24, 23, 963436, tzinfo=datetime.timezone.utc)),
        ),
    ]
