# Generated by Django 5.2.3 on 2025-06-21 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0025_city_region_remove_location_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 8, 40, 5, 241787, tzinfo=datetime.timezone.utc)),
        ),
    ]
