# Generated by Django 5.2.3 on 2025-06-21 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0026_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 8, 57, 26, 234327, tzinfo=datetime.timezone.utc)),
        ),
    ]
