# Generated by Django 5.2.3 on 2025-07-23 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0030_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 24, 14, 14, 36, 974807, tzinfo=datetime.timezone.utc)),
        ),
    ]
