# Generated by Django 5.2.3 on 2025-07-28 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0031_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 14, 21, 41, 408408, tzinfo=datetime.timezone.utc)),
        ),
    ]
