# Generated by Django 5.2.3 on 2025-07-28 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0032_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 14, 34, 8, 439066, tzinfo=datetime.timezone.utc)),
        ),
    ]
