# Generated by Django 5.2.3 on 2025-07-28 17:01

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0033_alter_story_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='admins',
            field=models.ManyToManyField(related_name='admin_of_centers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 17, 1, 47, 533502, tzinfo=datetime.timezone.utc)),
        ),
    ]
